
[gcp_service_account]
type = "service_account"
project_id = "purchaseapp-479012"
private_key_id = "799d779a6a30dc57eb05e97b16096b3e31b79ad9"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCmZmsCAaru/NRT
xXXBMhxNRp+fD1Ufigx33egzfZn6xUGHEdGmHWu3xeWt7NxcwlC+yj743nSgnvP2
AJax6v5UJ+ABMMHjeGmPJZPvP0bNAefV+N3mDupkMoPbYHdB8kU1T4mbIu6Wm/K4
6PvXoKRBcipurPxS/apuJf40xT2ROenp8LKoyHK2ltaupRsD1mz+L4bZkNT7QALW
JmrkMwbiVUl7SPnIM6oAeipNLrwEpbNAkqe+yhoTQa/73Ba5uR8lsWZ40aKEtNVw
dHCarmaNCuzY7QzUmlYY26Ctf9kFyQLSWKmLnD8+xXfG8aBx2O9oW003qYzm7irP
z0Qi6D5HAgMBAAECggEABkzzeVB52fG90mw0ILwWgUCO07V/aiHOhg1jeOulFG86
o3QjxY/wn7VBFJxW3bZH22mKB99YeCp8n1B3ZEY7GhGmdDUV6liJWq+4EcOKGUIc
tqflMwxWiLO29WwKJ/eV8kZQNg0VDqPaBXFg89Gz1nyNqcIoDbZoKSKMJRBg2+pP
Ps4Ljp/UKKRTZmBNZ174kNqSJSe8zJH5mMy2keepzy/oqGxhKRQ175AtI9ylZFFi
wk3fnLf8fXcamQFwP1nt/2zcmmVOku87J4sS0VPK0zn8b8Mfk4fs82skZooGOnej
Kx0aQlwKKfFu9Mc7jdL6JpSgS5WG3M0sLllczsGrBQKBgQDleK0HVx7GC52rmp+e
hYIm61iS7Ucry6dyr0VUHY7yQXZ3ruwwt9AfNoWtsgWMIpePhYe5RjjGzGuqnyuP
GjhZGOl64ta6dIJTFTbBPyWF4ls8bgHZFvqvtBKWtuTm1njnMVrK41DZ1q1JEttZ
d1QdwHpvh3iwJTaXJJdqNKHirQKBgQC5ox0m5Cqmr/p0GNloGc8zDtqQS59yKwdK
sc7yFtOQsqTBJ5tLNX1HpyA1Abo1Z+7FHDV+vEjHpmg/o1pPhhtGwuD8bTAxitO+
k1adATQqKzIfWCMHucE7Rkp54HwFX8MRzW1Z1qK4tn0WLilUBd0T7qvnhMcFrcBY
93ORFcn3QwKBgQCuH+4cPc2KNlJEXyZ0IZbrdXZWt1pkLzs22SzgcTWBOo9srf1n
0nNI3BSAAzAWcEFVlNuyiUiYAZJJfFKPWjQb172DlBGglrw100kjRolwmJzmtAsO
8lLzdM8OMmZri59ev6LHhcpaIn6HjpmHv/bCRMYjT0cTUomkEw4adynIWQKBgBxe
N9M8pOPqGozpSzfkUcyMpYvNcqVAvBGHEIfgQx5mnlTCF7Irj2SGvp47EFie9Fb8
05P1c+3GmUG4VdG3Pa3XlAgfK3E2tNr3qxG9IFqdVUCC+H9yvHuxZyouyuULWET9
Lou/CAjQIldkYH5tkvY7z9tGaB+PCMjPr8JpIP7/AoGBAJY194lZrMoMPyEGPIG9
Hco/p6K+DIpgNlRGKjL5g0chcPLgTvXmYVDOlliwZx84aCDV3JcGeehz8wdv2l4i
mj6JFNymIMEFfArWXOc/PaRrGyaRgm7dmMEVS/6gHJ2ybSG+El6H4reE0ySpbuYS
/E2SayPoNEVcyqmGPJ/EAFt2
-----END PRIVATE KEY-----"""
client_email = "purchaseapp@purchaseapp-479012.iam.gserviceaccount.com"
client_id = "108222693122847820601"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/purchaseapp%40purchaseapp-479012.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
